package com.mine.gublog.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   文章内容表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bams_article_content
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BamsArticleContent {
    /**
     * Database Column Remarks:
     *   主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article_content.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   文章内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article_content.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article_content.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article_content.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   文章id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article_content.article_id
     *
     * @mbg.generated
     */
    private Long articleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article_content.id
     *
     * @return the value of bams_article_content.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article_content.id
     *
     * @param id the value for bams_article_content.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article_content.content
     *
     * @return the value of bams_article_content.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article_content.content
     *
     * @param content the value for bams_article_content.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article_content.create_time
     *
     * @return the value of bams_article_content.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article_content.create_time
     *
     * @param createTime the value for bams_article_content.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article_content.update_time
     *
     * @return the value of bams_article_content.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article_content.update_time
     *
     * @param updateTime the value for bams_article_content.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article_content.article_id
     *
     * @return the value of bams_article_content.article_id
     *
     * @mbg.generated
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article_content.article_id
     *
     * @param articleId the value for bams_article_content.article_id
     *
     * @mbg.generated
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }
}