package com.mine.gublog.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   文章信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bams_article
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BamsArticle {
    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   标题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     * Database Column Remarks:
     *   作者id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     * Database Column Remarks:
     *   分类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.category_id
     *
     * @mbg.generated
     */
    private Long categoryId;

    /**
     * Database Column Remarks:
     *   封面图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.cover
     *
     * @mbg.generated
     */
    private String cover;

    /**
     * Database Column Remarks:
     *   状态 0:禁用, 1:暂存, 2:发布
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   发布时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.publish_time
     *
     * @mbg.generated
     */
    private Date publishTime;

    /**
     * Database Column Remarks:
     *   上次修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.edit_time
     *
     * @mbg.generated
     */
    private Date editTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   内容id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bams_article.content_id
     *
     * @mbg.generated
     */
    private Long contentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.id
     *
     * @return the value of bams_article.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.id
     *
     * @param id the value for bams_article.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.title
     *
     * @return the value of bams_article.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.title
     *
     * @param title the value for bams_article.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.user_id
     *
     * @return the value of bams_article.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.user_id
     *
     * @param userId the value for bams_article.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.category_id
     *
     * @return the value of bams_article.category_id
     *
     * @mbg.generated
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.category_id
     *
     * @param categoryId the value for bams_article.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.cover
     *
     * @return the value of bams_article.cover
     *
     * @mbg.generated
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.cover
     *
     * @param cover the value for bams_article.cover
     *
     * @mbg.generated
     */
    public void setCover(String cover) {
        this.cover = cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.status
     *
     * @return the value of bams_article.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.status
     *
     * @param status the value for bams_article.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.publish_time
     *
     * @return the value of bams_article.publish_time
     *
     * @mbg.generated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.publish_time
     *
     * @param publishTime the value for bams_article.publish_time
     *
     * @mbg.generated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.edit_time
     *
     * @return the value of bams_article.edit_time
     *
     * @mbg.generated
     */
    public Date getEditTime() {
        return editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.edit_time
     *
     * @param editTime the value for bams_article.edit_time
     *
     * @mbg.generated
     */
    public void setEditTime(Date editTime) {
        this.editTime = editTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.create_time
     *
     * @return the value of bams_article.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.create_time
     *
     * @param createTime the value for bams_article.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bams_article.content_id
     *
     * @return the value of bams_article.content_id
     *
     * @mbg.generated
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bams_article.content_id
     *
     * @param contentId the value for bams_article.content_id
     *
     * @mbg.generated
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }
}