package com.mine.gublog.entity;

import java.util.Date;

/**
 * Database Table Remarks:
 *   文件信息表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table fms_file
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class FmsFile {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   文件名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.filename
     *
     * @mbg.generated
     */
    private String filename;

    /**
     * Database Column Remarks:
     *   url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   业务名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.business
     *
     * @mbg.generated
     */
    private String business;

    /**
     * Database Column Remarks:
     *   本地路径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.location_path
     *
     * @mbg.generated
     */
    private String locationPath;

    /**
     * Database Column Remarks:
     *   状态 0:禁用，1:启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fms_file.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.id
     *
     * @return the value of fms_file.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.id
     *
     * @param id the value for fms_file.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.filename
     *
     * @return the value of fms_file.filename
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.filename
     *
     * @param filename the value for fms_file.filename
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.url
     *
     * @return the value of fms_file.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.url
     *
     * @param url the value for fms_file.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.business
     *
     * @return the value of fms_file.business
     *
     * @mbg.generated
     */
    public String getBusiness() {
        return business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.business
     *
     * @param business the value for fms_file.business
     *
     * @mbg.generated
     */
    public void setBusiness(String business) {
        this.business = business;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.location_path
     *
     * @return the value of fms_file.location_path
     *
     * @mbg.generated
     */
    public String getLocationPath() {
        return locationPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.location_path
     *
     * @param locationPath the value for fms_file.location_path
     *
     * @mbg.generated
     */
    public void setLocationPath(String locationPath) {
        this.locationPath = locationPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.status
     *
     * @return the value of fms_file.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.status
     *
     * @param status the value for fms_file.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.create_time
     *
     * @return the value of fms_file.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.create_time
     *
     * @param createTime the value for fms_file.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fms_file.update_time
     *
     * @return the value of fms_file.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fms_file.update_time
     *
     * @param updateTime the value for fms_file.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}