package com.mine.gublog.dao;

import com.mine.gublog.entity.BamsArticle;
import com.mine.gublog.entity.BamsArticleExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface BamsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    long countByExample(BamsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int deleteByExample(BamsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int insert(BamsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int insertSelective(BamsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    List<BamsArticle> selectByExample(BamsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    BamsArticle selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BamsArticle record, @Param("example") BamsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BamsArticle record, @Param("example") BamsArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BamsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BamsArticle record);
}