package com.mine.gublog.dao;

import com.mine.gublog.entity.BamsArticleCategory;
import com.mine.gublog.entity.BamsArticleCategoryExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * 2019/11/29: 新增分页查询
 */
@Mapper
public interface BamsArticleCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    long countByExample(BamsArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int deleteByExample(BamsArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int insert(BamsArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int insertSelective(BamsArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    List<BamsArticleCategory> selectByExample(BamsArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    BamsArticleCategory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BamsArticleCategory record, @Param("example") BamsArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BamsArticleCategory record, @Param("example") BamsArticleCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BamsArticleCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bams_article_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BamsArticleCategory record);

    /**
     * 分页查询
     * @param page
     * @param limit
     * @param map
     * @return
     */
    List selectCategoryListWithPage(Integer page, Integer limit, @Param("paramMap") Map<String,String> map);

}