package com.mine.gublog.dao;

import com.mine.gublog.entity.FmsFile;
import com.mine.gublog.entity.FmsFileExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface FmsFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    long countByExample(FmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int deleteByExample(FmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int insert(FmsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int insertSelective(FmsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    List<FmsFile> selectByExample(FmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    FmsFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FmsFile record, @Param("example") FmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FmsFile record, @Param("example") FmsFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FmsFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fms_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FmsFile record);
}