package com.mine.gublog.dao;

import com.mine.gublog.entity.UmsUser;
import com.mine.gublog.entity.UmsUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface UmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    long countByExample(UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int deleteByExample(UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int insert(UmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int insertSelective(UmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    List<UmsUser> selectByExample(UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    UmsUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UmsUser record, @Param("example") UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UmsUser record, @Param("example") UmsUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ums_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UmsUser record);
}